services:
  redis:
    image: redis:7-alpine
    container_name: collab_commerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: collab_commerce_web
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p ${PORT} collab_commerce.asgi:application
      "
    volumes:
      - ./collab_commerce:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      SECRET_KEY: django-insecure-dev-only
      DEBUG: "True"
      DJANGO_SETTINGS_MODULE: collab_commerce.settings

      REDIS_URL: redis://redis:6379/0
      REDIS_HOST: redis
      REDIS_PORT: 6379

    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  static_volume:
  media_volume:
