"""
Django settings for collab_commerce project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-vw_*!00ue)v3i5p39zgx-yqb85)l1x#76xd=-d6_4o6*+($)4@')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']
# CSRF_TRUSTED_ORIGINS = [
#     "https://*.up.railway.app",
# ]

# SECRET_KEY = os.environ["SECRET_KEY"]

DEBUG = os.environ.get("DEBUG", "False") == "True"

# Get Railway domain if available, otherwise use defaults
RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "")
ALLOWED_HOSTS_ENV = os.environ.get("ALLOWED_HOSTS")

if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(",")]
elif RAILWAY_PUBLIC_DOMAIN:
    # Use Railway's public domain - allow both exact domain and wildcard
    ALLOWED_HOSTS = [
        RAILWAY_PUBLIC_DOMAIN,
        '.railway.app',  # Allow all Railway subdomains
        'localhost',
        '127.0.0.1'
    ]
else:
    # Fallback for local development
    ALLOWED_HOSTS = ['.railway.app', 'localhost', '127.0.0.1', '*']

# CSRF trusted origins
# Note: Django does NOT support wildcards in CSRF_TRUSTED_ORIGINS
# Must use exact domains
CSRF_TRUSTED_ORIGINS_ENV = os.environ.get("CSRF_TRUSTED_ORIGINS")
if CSRF_TRUSTED_ORIGINS_ENV:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CSRF_TRUSTED_ORIGINS_ENV.split(",")]
else:
    # Build CSRF_TRUSTED_ORIGINS list
    CSRF_TRUSTED_ORIGINS = []
    
    # Add Railway public domain if available (exact domain required)
    if RAILWAY_PUBLIC_DOMAIN:
        CSRF_TRUSTED_ORIGINS.extend([
            f"https://{RAILWAY_PUBLIC_DOMAIN}",
            f"http://{RAILWAY_PUBLIC_DOMAIN}",  # Include HTTP for development
        ])
    
    # Add local development origins
    if DEBUG:
        CSRF_TRUSTED_ORIGINS.extend([
            "http://localhost:8000",
            "http://127.0.0.1:8000",
            "http://localhost",
            "http://127.0.0.1",
        ])
    
    # Remove duplicates while preserving order
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))
    
    # If no origins set, add a default (for Railway)
    if not CSRF_TRUSTED_ORIGINS:
        # Fallback - you should set CSRF_TRUSTED_ORIGINS env var with exact domain
        CSRF_TRUSTED_ORIGINS = ["https://shopcircle.up.railway.app"]

# Security settings for production
# In production (DEBUG=False), use secure cookies
# In development (DEBUG=True), allow non-secure cookies for easier testing
SESSION_COOKIE_SECURE = not DEBUG  # Only secure in production
CSRF_COOKIE_SECURE = not DEBUG  # Only secure in production
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Additional CSRF settings for Railway
CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token (needed for AJAX)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'channels',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'collab_commerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Add this line
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'collab_commerce.wsgi.application'
# Make sure to point to the asgi.py file
ASGI_APPLICATION = 'collab_commerce.asgi.application'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Channel layer configuration (using Redis)
# Make sure your Redis server is running
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.environ.get('REDIS_PORT', 6379))

from urllib.parse import urlparse

REDIS_URL = os.environ.get("REDIS_URL")
REDIS_PUBLIC_URL = os.environ.get("REDIS_PUBLIC_URL")  # Railway Redis public URL (avoid - incurs egress fees)

# Use Redis if available, otherwise fall back to InMemoryChannelLayer for Railway
# IMPORTANT: Always prefer REDIS_URL (private endpoint) over REDIS_PUBLIC_URL to avoid egress fees
if REDIS_URL:
    # Use private REDIS_URL (no egress fees, faster, recommended)
    redis_url = REDIS_URL
elif REDIS_PUBLIC_URL:
    # Fallback to public URL only if private URL not available (not recommended)
    redis_url = REDIS_PUBLIC_URL
    import sys
    print("WARNING: Using REDIS_PUBLIC_URL (public endpoint) - this incurs egress fees!", file=sys.stderr)
    print("Please use REDIS_URL (private endpoint) instead.", file=sys.stderr)

# Parse Redis URL for channels_redis if we have a Redis URL
if REDIS_URL or REDIS_PUBLIC_URL:
    # Railway format examples:
    # - redis://default:password@hostname:port
    # - redis://hostname:port
    import sys
    try:
        parsed = urlparse(redis_url)
        redis_host = parsed.hostname or 'localhost'
        redis_port = parsed.port or 6379
        redis_password = parsed.password
        redis_username = parsed.username or 'default'
        
        # Log Redis connection info (without password)
        print(f"Connecting to Redis at {redis_host}:{redis_port}", file=sys.stderr)
        
        # channels_redis 4.x supports both URL strings and tuple format
        # For Railway with password, we need to use the URL format or build connection dict
        if redis_password:
            # Build connection configuration with password
            # channels_redis can handle URL strings directly in newer versions
            CHANNEL_LAYERS = {
                "default": {
                    "BACKEND": "channels_redis.core.RedisChannelLayer",
                    "CONFIG": {
                        "hosts": [redis_url],  # channels_redis 4.x supports full URL
                    },
                },
            }
            print("Redis configured with password authentication", file=sys.stderr)
        else:
            # No password, use tuple format (simpler and more reliable)
            CHANNEL_LAYERS = {
                "default": {
                    "BACKEND": "channels_redis.core.RedisChannelLayer",
                    "CONFIG": {
                        "hosts": [(redis_host, redis_port)],
                    },
                },
            }
            print("Redis configured without password", file=sys.stderr)
    except Exception as e:
        # If parsing fails, try using URL directly
        # This works with channels_redis 4.x
        print(f"Redis URL parsing failed, using URL directly: {str(e)}", file=sys.stderr)
        CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [redis_url],
                },
            },
        }
    print("Redis channel layer configured successfully", file=sys.stderr)
else:
    # Fallback for Railway if Redis is not configured
    # WARNING: InMemoryChannelLayer doesn't work across multiple instances
    # and doesn't persist between restarts - only for single-instance development
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
    # Log warning about using InMemoryChannelLayer
    import sys
    print("WARNING: Redis not configured! Using InMemoryChannelLayer.", file=sys.stderr)
    print("Shared cart and chat will NOT work properly across multiple users.", file=sys.stderr)
    print("Please add Redis service in Railway and set REDIS_URL environment variable.", file=sys.stderr)

# Database configuration - Use PostgreSQL on Railway, SQLite locally
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Parse DATABASE_URL (Railway format: postgresql://user:pass@host:port/dbname)
    # Handle both postgresql:// and postgres:// schemes
    if DATABASE_URL.startswith('postgres://'):
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
    
    url = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': url.path[1:] if url.path.startswith('/') else url.path,  # Remove leading '/'
            'USER': url.username or '',
            'PASSWORD': url.password or '',
            'HOST': url.hostname or 'localhost',
            'PORT': url.port or 5432,
        }
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# In settings.py

# ... (rest of your settings)

# Cashfree Payment Gateway Settings
CASHFREE_APP_ID = os.getenv("CASHFREE_APP_ID")
CASHFREE_SECRET_KEY = os.getenv("CASHFREE_SECRET_KEY")
CASHFREE_API_BASE = os.getenv("CASHFREE_API_BASE")

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'product_list'
LOGOUT_REDIRECT_URL = 'product_list'